omschrijving_croissantjes = input("omschrijving") 
aantal_croissantjes = int(input("aantal_croissantjes")) 
aantal_croissantjes = int(aantal_croissantjes) 
prijs_croissantjes = input("prijs_croissantjes") 
prijs_croissantjes = float(prijs_croissantjes)  
totale_prijs_croissantjes = aantal_croissantjes * prijs_croissantjes
print(aantal_croissantjes * prijs_croissantjes)
omschrijving_stokbroden = input("omschrijving:") 
aantal_stokbroden = input("aantal_stokbroden") 
aantal_stokbroden = int(aantal_stokbroden)
prijs_stokbroden = input("prijs_stokbroden") 
prijs_stokbroden = float(prijs_stokbroden) 
print(aantal_stokbroden * prijs_stokbroden) 
totale_prijs_stokbroden = aantal_stokbroden * prijs_stokbroden 
omschrijving_kortingsbonnen = input("omschrijving") 
aantal_kortingsbonnen = input("aantal") 
aantal_kortingsbonnen = int(aantal_kortingsbonnen) 
prijs_kortingsbonnen = input("prijs_kortingsbonnen")  
prijs_kortingsbonnen = float(prijs_kortingsbonnen) 
totale_prijs_kortingsbonnen = aantal_kortingsbonnen * prijs_kortingsbonnen  
totale_prijs = totale_prijs_kortingsbonnen + totale_prijs_croissantjes + totale_prijs_stokbroden
print(aantal_kortingsbonnen * prijs_kortingsbonnen) 
print(totale_prijs_kortingsbonnen + totale_prijs_stokbroden + totale_prijs_croissantjes)  
print(f"{aantal_croissantjes} {omschrijving_croissantjes} {prijs_croissantjes}")
print(f"{aantal_stokbroden} {omschrijving_stokbroden} {prijs_stokbroden}")
print(totale_prijs_croissantjes + totale_prijs_stokbroden + totale_prijs_kortingsbonnen)
print(f'de feestlunch kost je bij de bakker {totale_prijs} voor de {aantal_croissantjes} croissantjes en de {aantal_stokbroden} stokbroden als de {aantal_kortingsbonnen} kortingsbonnen nog geldig zijn')