naam = input("naam:")
print("naam: " + naam) 
adres = input("adres:")
print("adres: " + adres)
postcode = input("postcode:")
print("postcode: " + adres)
woonplaats = input("woonplaats:")
print("woonplaats: " + woonplaats) 

print(f'----------------------------')
print("naam: " + naam) 
print("adres: " + adres) 
print("postcode: " + postcode)
print("woonplaats: " + woonplaats) 
print(f'----------------------------') 